CREATE TABLE USERS (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    LOGIN VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    DATE_OF_REGISTRATION DATE NOT NULL,
    DESCRIPTION VARCHAR(2000),    
    UNIQUE UQ_LOGIN_1 (LOGIN),
    PRIMARY KEY (ID)
);
 
CREATE TABLE ROLES (
    ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    USER_ROLE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255),
    UNIQUE UQ_USER_ROLE_1 (USER_ROLE),
    PRIMARY KEY (id)
);
 
CREATE TABLE USERS_ROLES (
    USERS_ID INT UNSIGNED NOT NULL,
    ROLES_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (USERS_ID) REFERENCES USERS (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (ROLES_ID) REFERENCES ROLES (ID)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

CREATE TABLE warehouses (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    address VARCHAR(255) NOT NULL,
    UNIQUE UQ_ADDRESS_1 (address),
    PRIMARY KEY (id)
);
 
CREATE TABLE items (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    warehouse_id INT UNSIGNED,
    PRIMARY KEY (id),
    FOREIGN KEY (warehouse_id) REFERENCES warehouses (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);
 
CREATE TABLE providers (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    PRIMARY KEY (id)
);
 
CREATE TABLE items_providers (
    item_id INT UNSIGNED NOT NULL,
    provider_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (item_id) REFERENCES items (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    FOREIGN KEY (provider_id) REFERENCES providers (id)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);