INSERT INTO USERS (LOGIN, PASSWORD, DATE_OF_REGISTRATION, DESCRIPTION) VALUES ('vasya', 'vasya', '2016-07-30', 'Java developer');
INSERT INTO USERS (LOGIN, PASSWORD, DATE_OF_REGISTRATION, DESCRIPTION) VALUES ('kosta', 'kosta', '2016-05-01', 'C++ developer');
INSERT INTO USERS (LOGIN, PASSWORD, DATE_OF_REGISTRATION, DESCRIPTION) VALUES ('petya', 'petya', '2016-04-22', 'QA');
INSERT INTO USERS (LOGIN, PASSWORD, DATE_OF_REGISTRATION, DESCRIPTION) VALUES ('viktor', 'viktor', '2016-02-01', 'QA automatizator');
INSERT INTO USERS (LOGIN, PASSWORD, DATE_OF_REGISTRATION, DESCRIPTION) VALUES ('nikolay', 'nikolay', '2016-01-30', 'PM');
INSERT INTO USERS (LOGIN, PASSWORD, DATE_OF_REGISTRATION, DESCRIPTION) VALUES ('alexander', 'alexander', '2016-06-15', 'Java developer');

INSERT INTO ROLES (CODE, DESCRIPTION) VALUES (1, 'Admin');
INSERT INTO ROLES (CODE, DESCRIPTION) VALUES (2, 'Ordinal user');
INSERT INTO ROLES (CODE, DESCRIPTION) VALUES (2, 'Observer');

INSERT INTO USERS_ROLES (USERS_ID, ROLES_ID) VALUES (1, 1);
INSERT INTO USERS_ROLES (USERS_ID, ROLES_ID) VALUES (1, 2);
INSERT INTO USERS_ROLES (USERS_ID, ROLES_ID) VALUES (2, 2);
INSERT INTO USERS_ROLES (USERS_ID, ROLES_ID) VALUES (3, 2);
INSERT INTO USERS_ROLES (USERS_ID, ROLES_ID) VALUES (4, 2);
INSERT INTO USERS_ROLES (USERS_ID, ROLES_ID) VALUES (5, 2);
INSERT INTO USERS_ROLES (USERS_ID, ROLES_ID) VALUES (6, 2);